
<article class="body">


   <section class="content">
       <h2>ELECTRONIC CHEQUE PROCESSING </h2>
 
       <p>Recent major developments worldwide in the areas of negotiable instruments and payment and settlement systems have included the advancement of electronic cheques, payment cards, securities transfers, and payment transactions. A common theme is the adaptation by statute of the law to the world of electronic processing  or banking as it keeps evolving.</p>
       
       <p>The first development, outlined , is concerned with the ongoing transformation of the cheque payment into an electronic funds transfer. The cheque has been characterized as the paper-based payment system par excellence. Recently, this view has been eroded in several ways. Principal developments outlined herein  consist of the "electronic cheque" in the United States;  and Canada, the remotely created cheque in the United States and Canada; electronic presentment in the United States, UK, recent law reform in Sri Lanka and a proposal in Canada; and "electronic negotiation" under "cheque 21 Act" in the United States. A procedure in which the physical movement of cheques is curtailed or eliminated, being replaced, in whole or in part, by electronic transmission of information is called "cheque truncation." To a large extent, cheque truncation reflects a partial conversion of the cheque collection process to an electronic funds transfer.
       </p>
       
       <p>The evolving legal framework applicable to cheques, and payment cards. A fundamental distinction has been known to exist between  the two ...</p>
       
       <h2>Cheque Conversion</h2>
       
       <p>The next time you write a cheque to your local merchant, employee, contractor, supplier or utility company, the cashier may hand the cheque back to you after the payment ( cheque),  has been processed – electronically.    Or maybe you’re mailing a cheque as payment to a company. That payment, too, may also be processed electronically. Why? More merchants, companies, contractors, and companies are using electronic cheque conversion, which converts information from your paper cheque into an electronic cheque payment from your bank account. In fact, in the United Skates alone., NACHA – the Electronic Payments Association – estimates that more than 1.7 billion paper cheques were converted through in-store and mail-in transactions in 2005 alone.
       </p>

       <h1>How does electronic cheque conversion work?</h1>
       
       <p>When you give your cheque to a store cashier, the cheque is run through an electronic system that captures your bank account information and the amount of the cheque. You’re asked to sign a receipt and you get a copy for your records. When your cheque information has been processed and your cheque has been handed back to you, it should be voided or marked by the merchant so that it can’t be used again. The merchant electronically sends information from the cheque (but not the cheque itself) to your bank or other financial institution, and the funds are transferred into the merchant’s account.</p>
      
       
       <p>Electronic cheque conversion also may be used for cheques you mail to pay for a purchase or to pay on an account. The merchant or company receiving your cheque electronically sends information from your cheque (but not the cheque itself) through the system, and the funds are transferred into their account.</p>
       
       <h1>How will I know if companies I do business with use electronic cheque conversion?</h1>
       
       <p>By law, you must receive notice if your cheque information will be processed electronically. Notice can be given in different ways: In a store, a merchant might post a sign at the register or give you a written notice. For a mailed cheque, the company might include the notice on your monthly statement or under its terms and conditions. The notice also should state if the merchant or company will electronically collect from your account a fee – like a “bounced cheque” fee – if you have insufficient funds to cover the transaction.</p>
       
       <h1>Will I get my cheques back?</h1>
       
       <p>Your financial institution may be unable to give you a duplicate copy of your cheques, so it’s important to keep your cheques – and receipts – when the payment has been processed electronically in a store, especially if you need proof of payment. In the case of merchants and companies that use electronic cheque conversion for your mailed cheques, you won’t get your cheque back because the information was transmitted through the process only electronically. However, if you need a copy of the cheque, you can always ask the merchant or company if they’ll provide it to you. You could also consider using duplicate cheques, where you keep a copy of every cheque you write. There may be an extra charge for duplicate cheques, whether you buy them from your financial institution or a cheque printing company.</p>
       
<h1>Will the payment be shown on my monthly bank statement?</h1>
<p>Yes. Your bank statement must show the electronic transaction. It should include the name of the merchant or company, the payment amount, and the date the payment was electronically transferred from your account, and the transaction location. This information may be included in an area other than where your paper cheques are listed, so carefully review the entire statement. It's important to keep your bank statements; they can be used as proof of payment for your transactions.</p>
<h1>What does electronic cheque conversion mean to me?</h1>
<p>There may be no float on your cheque. That means, if you write a cheque today, you need to have funds in your account today to cover it. If you don't, your cheque may bounce and you may be charged a fee by the merchant, your financial institution, or both. Bounced cheques can blemish your credit record. If you're concerned about bounced cheques, you may want to consider overdraft protection or a backup line of credit on your account. Be aware, your financial institution may charge for these services.</p>
<h1>What if I find an error on my account?</h1>
<p>Promptly review your bank statement for errors. For example, did two payments go through instead of one? Were you charged the wrong amount for the item purchased? You have 60 days from the date your statement was sent to you to notify your financial institution of any errors. Your financial institution might take up to 45 days from the date you notify it to investigate the situation. In most instances, if it will take more than 10 business days, your financial institution must credit your account while it investigates the error.</p>
<h1>What if I find unauthorized transactions on my account?</h1>
<p>Generally, if you find unauthorized electronic cheque conversion on your account (or someone has fraudulently obtained your banking account information), notify your financial institution immediately. Your level of loss depends on how quickly you report the problem.</p>
<p>Under  USA federal law, for unauthorized electronic cheque conversion, you have 60 days to report these transfers after your bank account statement containing the problem is mailed to you. If you fail to report the unauthorized transfers within this time period, you risk losing all the money in your account and the unused portion of your maximum line of credit for overdrafts. It's also a good idea to report any other unauthorized transfers on your account or problems regarding any loss or theft of your cheques immediately,  however if you wrote a paper cheque, then its likely you intended to pay the individual, company, or creditor, listed in the electronic and or paper cheque descriptor of your bank statement.</p>
<p> </p>
<h2>Keeping Close Tabs on Your Account</h2>
<h1>The Federal Trade Commission suggests that you:</h1>
<ul>
<li>Keep track of deposits. Make sure you record all deposits to your cheque account in your chequebook immediately. When you make deposits, save the receipts. They can help resolve mistakes.<br />
  </li><li>Remember to record all automatic or Electronic Fund Transfer (EFT) deposits, such as your paycheque, in your chequebook  or also provide with drawls based on cheques you've written including electronic cheques when they occur in your account.<br />
  </li><li>Keep track of withdrawals. Immediately record your transactions. This includes: cheques you write and electronic cheque conversion; ATM withdrawals; debit card transactions; preauthorized withdrawals; online transfers you make; and fees or service charges, including ATM fees.<br />
  </li><li>Promptly balance your account when your statement arrives. This means reconciling the information you have recorded in your chequebook against the statement your financial institution sends to you. Review your entire bank statement; electronic cheque conversion may be recorded in an area other than where your paper cheques are listed, such as under &quot;other withdrawals.&quot;<br />
  </li><li>Review your statement to be sure your cheques were only processed once and for the correct amount. If your account won't balance, and you can't find the error, promptly call your financial institution for help.<br />
  </li><li>Be especially careful with telephone and online transactions. If a merchant or company lets you make a payment using cheque information for a phone or Web transaction, they should inform you that they will process your payment electronically. Your bank and chequeing account numbers will be requested as they appear at the bottom of your cheque, along with permission to charge the account for the item you're paying for. Your transaction will then be processed and the funds withdrawn from your account and deposited in the merchant or company's account electronically.<br />
  </li><li> Be especially cautious about sharing your bank and cheque account numbers. Do not give out personal information – particularly on the telephone, by e-mail or otherwise online – unless you have initiated the contact or know who you're dealing with. Scam artists can use your personal information to commit fraud – such as identity theft. That's where someone uses your personal information, such as your cheque account number, Social Security number, mother's maiden name, or birth date, without your knowledge or permission, to commit fraud or theft.<br />
</li><li>substitute cheque (also called an Image Replacement Document or &quot;IRD&quot;),   is a negotiable instrument used in the United States to represent the digital reproduction of an original paper cheque. As a negotiable instrument, a substitute cheque maintains the status of a &quot;legal cheque&quot; in lieu of the original cheque as authorized under the United States law cheque Clearing for the 21st Century Act (cheque 21 Act). Instead of presenting the original paper cheques, financial institutions and payment processing centers electronically transmit data from substitute cheques for settlement through the Federal Reserve System</p>
</li></ul>
<p>Substitute cheques are recognized as legal cheques as long as the instruments meet specific requirements. These requirements include the faithful reproduction of the paper cheque Under the cheque 21 Act, payment instruments that are eligible for conversion into substitute cheques include consumer (personal) cheques, commercial (business) cheques, money orders, traveler's cheques and treasury cheques.  The cheque 21 Act permits any financial institution (such as a commercial bank or credit union) that participates in the cheque collection process to remove or &quot;truncate&quot; the original cheque from the forward collection or return process without first requiring an existing agreement between the bank of first deposit (BOFD) and the paying bank.</p>
<p> The elimination of the original paper cheques from the clearing process saves the banking industry the costs of handling, sorting, transporting, storing, guarding, and mailing paper cheques. After the bank truncates the original cheques in favor of substitute cheques, the bank can store or archive the paper cheques, return them to its customers according to state law, or later destroy the cheques.</p>
<h1>Legal requirements</h1>
<p>A properly prepared substitute cheque is considered the legal equivalent of the original paper cheque that can be accepted for payment or proof of payment in the same manner as the original cheque. Every substitute cheque must adhere to the following requirements before it can be recognized as the legal equivalent of the original cheque:</p>
<ul>
    
    <li>The substitute cheque must accurately represent all information depicted on the front and back of the original cheque at the time the financial institution truncates the original cheque. The information includes the names of the payor and payee, courtesy and legal amounts, endorsements, and encoding information, among other details.<br />
  </li><li>The substitute cheque must accurately represent the MICR line of the original cheque.<br />
  </li><li>The substitute cheque must bear the legend &quot;This is a legal copy of your cheque. You can use it the same way you would use the original cheque.&quot;<br />
  </li><li>The financial institution or processor must provide a warranty for the substitute cheque when it removes or &quot;truncates&quot; the original paper cheque from the forward collection or return process and converts the paper cheque into a substitute cheque.<br />
  </li><li>The financial institution or processor that truncated the original cheque must follow standards in the capture of cheque images and MICR data when it produces the substitute cheque.<br />
  </li><li>Image statements that include pictures or images of the original paper cheques and/or substitute cheques, photocopies of the original cheques, and images of cheques posted online are not recognized as the legal equivalents of substitute cheques. Unlike a substitute cheque, a photocopy of a cheque cannot be presented through the cheque clearing process for settlement because the photocopy of the cheque does not adhere strictly to the requirements for substitute cheques under the cheque 21 Act</p>
</li><li>Since substitute cheques are considered legal &quot;cheques,&quot; substitute cheques are subject to existing cheque laws and regulations. Other laws and regulations that govern substitute cheques in the United States include the Expedited Funds Availability Act, Article 3 (Negotiable Instruments),[8] and Article 4 (Bank Deposits and Collections)[9] of the Uniform Commercial Code (UCC), along with a variety of state and federal regulatory laws. U.S. federal laws that also affect substitute cheques include Federal Reserve regulations that provide for recrediting the amount of the substitute cheque in the case of fraud and duplicate payments caused by settlement of both the substitute cheque and the original cheque used for creating the substitute cheque.[2][4][6] If any state law, federal law, or provision of the UCC conflicts with the cheque 21 Act, the cheque 21 Act takes precedence to the extent of the inconsistencies among those laws and provisions   , and in CANADA, similarly electronically processed cheques meet similar standards and regulations</p>
</li></ul>
    <h1>Clearing process</h1>
<p>Each substitute cheque processed for forward collection is encoded with a &quot;4&quot; as the External Processing Code or &quot;EPC&quot; in position 44 of the MICR line.    An example of the forward collection process for substitute cheques involves the following steps</p>
<ul>
    
    <li>The payee endorses the original paper cheque and presents it to the depository bank or clearer of first deposit.<br />
  </li><li>The bank of first deposit ,&quot;BOFD&quot; (Bank 1) or processor, processors agent,  stamps its endorsement on the rear of the original cheque.<br />
 </li><li> Bank 1 as the &quot;truncating&quot; bank captures an image of the front and back of the original cheque and the MICR line data from the front of the cheque. Bank 1 then removes (truncates) the original cheque from the clearing process.<br />
 </li><li> Bank 1 electronically transmits the cheque image and the MICR line data captured from the original cheque to its correspondent or intermediary bank (Bank 2). If no agreement exists between Bank 1 and Bank 2 to exchange cheque images and data, Bank 1 must provide either the original cheque or the legal equivalent of the substitute cheque to Bank 2.<br />
 </li><li> Bank 2 as the &quot;reconverting&quot; bank adds its electronic endorsement for the item to the record. The reconverting bank then uses the cheque image, MICR data, its own electronic endorsement, and the electronic endorsements received from Bank 1 to create a substitute cheque.<br />
 </li><li> Bank 2 presents the cheque image and MICR data to the paying bank (Bank 3) for settlement. If no agreement exists between Bank 2 and Bank 3, Bank 2 must provide Bank 3 with either the original cheque or a legal equivalent of the substitute cheque for the item.<br />
</li><li>  The paying bank (Bank 3) uses cheque image and MICR data or information from the substitute cheque received from the reconverting bank (Bank 2) to process the item during the normal course of settlement.<br />
 </li><li> After the settlement process, Bank 3 provides a copy of the substitute cheque to the customer who wrote the original cheque or includes information about the substitute cheque in that customer's monthly or periodic statement.<br />
 </li><li> Any financial institution or processor that participates in the forward collection (or return) process can become the reconverting bank if that bank creates the substitute cheque for transmittal and or settlement.</p>
 </li></ul>
     
     <p>If a substitute cheque must be returned unpaid because of insufficient funds, the paying bank (Bank 3) stamps the item NSF (non-sufficient funds) as the reason for the return. In this case, Bank 3 encodes a &quot;5&quot; as the EPC on the MICR line, along with the routing number of the depository bank and the dollar amount of the substitute cheque. Bank 3 encodes this information on a return strip, perforated strip, or carrier document that the bank attaches to the unpaid substitute cheque.   The paying bank then returns the unpaid substitute cheque through the routing process to the BOFD (Bank 1)  or processor, processors agent, for further handling. Once Bank 1 receives the returned substitute cheque, the bank issues a charge back notice to its customer who deposited or offered the cheque for settlement.</p>
<p> </p>
<p>·       and warranty of the instrument by the reconverting bank—the bank that created the substitute cheques or the first bank that transferred or presented them during the cheque clearing process Substitute cheques are also subject to the Uniform Commercial Code (UCC), existing federal and state cheque laws, and regulations specific to consumer rights that affect the acceptance of these instruments,.   Although substitute cheques are subject to the UCC and existing state and federal cheque laws, the cheque 21 Act takes precedence over these other laws and regulations for substitute cheques]</p>
<h1>Remote deposit</h1>
<p>According to  Wikipedia, the free encyclopedia</p>
<p>Remote deposit refers to the ability to deposit a cheque into a bank account from a remote location, such as an office or home, without having to physically deliver the cheque to the bank. This is typically accomplished by scanning a digital image of a cheque into a computer, then transmitting that image to the bank, a practice that became legal in the United States in 2004 when the cheque Clearing for the 21st Century Act (or cheque 21 Act) took effect. This service is typically used by businesses, though a remote deposit application for consumers has been developed  and has begun to be implemented by a handful of banks and processors  in Canada and United States.  It should not be confused with debit or credit card processing.</p>
       
    </section>
        


</article>
